Update README.md
Added dependencies to fix missing files:

"./boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory"